# Generated by Django 5.1 on 2026-03-22 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('github_url', models.URLField()),
                ('webhook_secret', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'repositories',
                'ordering': ['-created_at'],
            },
        ),
    ]
