# Generated by Django 5.1 on 2026-03-22 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0002_initial'),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('files_changed', models.JSONField(default=list)),
                ('total_additions', models.IntegerField(default=0)),
                ('total_deletions', models.IntegerField(default=0)),
                ('filtered_files', models.JSONField(default=list)),
                ('raw_diff', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('webhook_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr_diff', to='webhooks.webhookevent')),
            ],
            options={
                'db_table': 'pr_diffs',
            },
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('overall_score', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('model_used', models.CharField(default='llama3-8b-8192', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ai_raw_response', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='repositories.repository')),
                ('webhook_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_review', to='webhooks.webhookevent')),
                ('pr_diff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_review', to='reviews.prdiff')),
            ],
            options={
                'db_table': 'code_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('suggestion', 'Suggestion')], max_length=20)),
                ('issue_type', models.CharField(choices=[('security', 'Security'), ('performance', 'Performance'), ('style', 'Style'), ('logic', 'Logic'), ('bug', 'Bug')], max_length=20)),
                ('message', models.TextField()),
                ('suggestion', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reviews.codereview')),
            ],
            options={
                'db_table': 'review_issues',
                'ordering': ['severity', 'file_path'],
            },
        ),
    ]
