# Generated by Django 5.0.14 on 2026-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='model_used',
            field=models.CharField(default='llama-3.1-8b-instant', max_length=100),
        ),
    ]
